// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFbz0OuLEpZ_WxCuyhcj_r41O9ouNGFfg',
    appId: '1:442386894936:web:9f2f14832aa03979253a2d',
    messagingSenderId: '442386894936',
    projectId: 'com.umuttopalak.finance_tracking',
    authDomain: 'com.umuttopalak.finance_tracking.firebaseapp.com',
    storageBucket: 'com.umuttopalak.finance_tracking.appspot.com',
    measurementId: 'G-ZMYZYYSQ17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmt6UpIv8oI26w1KcGFrsfXw5fexvq1MA',
    appId: '1:442386894936:android:7e862588b80c8024253a2d',
    messagingSenderId: '442386894936',
    projectId: 'com.umuttopalak.finance_tracking',
    storageBucket: 'com.umuttopalak.finance_tracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwT7my4cPSQmL3Ur3lwhZr_dBWIX9xPdc',
    appId: '1:442386894936:ios:a5205b0272386e16253a2d',
    messagingSenderId: '442386894936',
    projectId: 'com.umuttopalak.finance_tracking',
    storageBucket: 'com.umuttopalak.finance_tracking.appspot.com',
    iosBundleId: 'com.umuttopalak.finance_tracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwT7my4cPSQmL3Ur3lwhZr_dBWIX9xPdc',
    appId: '1:442386894936:ios:a5205b0272386e16253a2d',
    messagingSenderId: '442386894936',
    projectId: 'com.umuttopalak.finance_tracking',
    storageBucket: 'com.umuttopalak.finance_tracking.appspot.com',
    iosBundleId: 'com.umuttopalak.finance_tracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFbz0OuLEpZ_WxCuyhcj_r41O9ouNGFfg',
    appId: '1:442386894936:web:120bd2847003708a253a2d',
    messagingSenderId: '442386894936',
    projectId: 'com.umuttopalak.finance_tracking',
    authDomain: 'com.umuttopalak.finance_tracking.firebaseapp.com',
    storageBucket: 'com.umuttopalak.finance_tracking.appspot.com',
    measurementId: 'G-Y1767VV9SX',
  );

}